name=TEA5767
version=1.0.0
author=Volodymyr Kumpan
maintainer=Volodymyr Kumpan <v.kumpan@outlook.com>
sentence=Arduino library for controlling TEA5767 FM radio module.
paragraph=Provides a driver and examples for tuning, scanning, mute/unmute, stereo/mono, and standby control.
category=Signal Input/Output
url=https://github.com/vkumpan/TEA5767
architectures=avr